//! ADR-009: Permanently frozen legacy audit entry type (`AuditEntryV1Legacy`).
//!
//! ## CRITICAL IMMUTABILITY CONTRACT
//!
//! **This struct is permanently frozen.** You MUST NOT add, remove, reorder,
//! rename, or change the type of any field. You MUST NOT modify any `serde`
//! attribute. Doing so will silently break HMAC-SHA256 verification of every
//! historical audit log ever written by agentwall <= v1.x.
//!
//! The active application struct (`AuditEntry` in `logger.rs`) can evolve
//! freely — only this frozen copy is used by the verifier for legacy entries.
//!
//! See: `docs/adr/ADR-009-audit-chain-migration.md`

use hmac::{Hmac, Mac};
use serde::{Deserialize, Serialize};
use sha2::Sha256;

type HmacSha256 = Hmac<Sha256>;

/// Permanently frozen historical schema for legacy entries (where `schema_version`
/// is absent from the JSON line).
///
/// **NEVER** add, reorder, rename, or modify fields or attributes in this struct.
/// Any change will break HMAC chain verification of historical logs.
///
/// Field order matches the original `AuditEntry` struct at commit v1.0.93 exactly.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuditEntryV1Legacy {
    /// RFC-3339 timestamp at write time.
    pub ts: String,
    /// Session UUID generated by the gateway.
    pub session_id: String,
    /// Event name (e.g. `tool_allow`, `tool_deny`).
    pub event: String,
    /// Tool name from the MCP `tools/call` request.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_name: Option<String>,
    /// SHA-256 hex of the canonical JSON of the tool arguments.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub params_hash: Option<String>,
    /// Raw params — only present when `include_params = true`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub params: Option<serde_json::Value>,
    /// Human-readable denial or event reason.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    /// Policy evaluation latency in milliseconds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub latency_ms: Option<f64>,
    /// OIDC `sub` claim.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub identity_sub: Option<String>,
    /// OIDC `email` claim.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub identity_email: Option<String>,
    /// SHA-256 hash of the active policy file at event time.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub policy_hash: Option<String>,
    /// Client remote IP address.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub request_ip: Option<String>,
    /// Group policy ID that triggered this decision.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub matched_group_id: Option<String>,
    /// Zero-based position within the current log file.
    pub entry_index: u64,
    /// HMAC hex of the previous entry (ZERO_HMAC for the first entry).
    pub prev_hmac: String,
    /// HMAC-SHA256 of this entry's canonical JSON (with `hmac` field set to None).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hmac: Option<String>,
}

impl AuditEntryV1Legacy {
    /// Recompute the HMAC of this legacy entry using the frozen serialization format.
    ///
    /// This method strips the `hmac` field, re-serializes via `serde_json::to_string`
    /// (which respects the frozen field order and `skip_serializing_if` attributes),
    /// and computes HMAC-SHA256.
    pub fn compute_hmac(&self, session_secret: &[u8]) -> Result<String, String> {
        let mut verify_copy = self.clone();
        verify_copy.hmac = None;

        let canonical = serde_json::to_string(&verify_copy)
            .map_err(|e| format!("legacy v1 re-serialization error: {}", e))?;

        let mut mac = HmacSha256::new_from_slice(session_secret).expect("HMAC key length is valid");
        mac.update(canonical.as_bytes());
        Ok(hex::encode(mac.finalize().into_bytes()))
    }

    /// Verify that the stored HMAC matches a freshly computed one.
    pub fn verify_hmac(&self, session_secret: &[u8]) -> Result<bool, String> {
        let stored = self.hmac.as_deref().unwrap_or_default();
        let computed = self.compute_hmac(session_secret)?;
        Ok(stored == computed)
    }
}

// ─── Pinned Serialization Tests ────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    /// Proves that the serialization byte output is stable. If this test fails,
    /// someone has modified the frozen struct — which is a contract violation.
    #[test]
    fn test_serialization_byte_stability() {
        let entry = AuditEntryV1Legacy {
            ts: "2026-01-01T00:00:00+00:00".to_string(),
            session_id: "test-session-id".to_string(),
            event: "tool_allow".to_string(),
            tool_name: Some("read_file".to_string()),
            params_hash: None,
            params: None,
            reason: None,
            latency_ms: Some(1.5),
            identity_sub: None,
            identity_email: None,
            policy_hash: None,
            request_ip: None,
            matched_group_id: None,
            entry_index: 0,
            prev_hmac: "0000000000000000000000000000000000000000000000000000000000000000"
                .to_string(),
            hmac: None,
        };

        let json = serde_json::to_string(&entry).unwrap();

        // Verify expected field order and skip_serializing_if behavior.
        // The key assertion is that re-running this test on any future version
        // of the crate produces the exact same bytes.
        assert!(json.contains("\"ts\":\"2026-01-01T00:00:00+00:00\""));
        assert!(json.contains("\"tool_name\":\"read_file\""));
        assert!(json.contains("\"latency_ms\":1.5"));
        assert!(!json.contains("\"params_hash\"")); // None → omitted
        assert!(!json.contains("\"params\"")); // None → omitted
        assert!(!json.contains("\"reason\"")); // None → omitted
        assert!(!json.contains("\"hmac\"")); // None → omitted

        // Pin the exact byte length as a canary.
        let expected = r#"{"ts":"2026-01-01T00:00:00+00:00","session_id":"test-session-id","event":"tool_allow","tool_name":"read_file","latency_ms":1.5,"entry_index":0,"prev_hmac":"0000000000000000000000000000000000000000000000000000000000000000"}"#;
        assert_eq!(json, expected, "Frozen struct serialization has drifted!");
    }

    /// Proves round-trip fidelity: deserialize then re-serialize produces identical bytes.
    #[test]
    fn test_round_trip_fidelity() {
        let original = r#"{"ts":"2026-01-01T00:00:00+00:00","session_id":"s1","event":"tool_deny","tool_name":"bash","reason":"blocked","entry_index":3,"prev_hmac":"abcd","hmac":"ef01"}"#;
        let parsed: AuditEntryV1Legacy = serde_json::from_str(original).unwrap();
        let reserialized = serde_json::to_string(&parsed).unwrap();
        assert_eq!(
            original, reserialized,
            "Round-trip serialization drift detected"
        );
    }

    /// HMAC computation must be deterministic for identical inputs.
    #[test]
    fn test_hmac_determinism() {
        let entry = AuditEntryV1Legacy {
            ts: "2026-06-15T12:00:00Z".to_string(),
            session_id: "hmac-test".to_string(),
            event: "tool_allow".to_string(),
            tool_name: Some("git_status".to_string()),
            params_hash: None,
            params: None,
            reason: None,
            latency_ms: None,
            identity_sub: None,
            identity_email: None,
            policy_hash: None,
            request_ip: None,
            matched_group_id: None,
            entry_index: 0,
            prev_hmac: "0000000000000000000000000000000000000000000000000000000000000000"
                .to_string(),
            hmac: Some("placeholder".to_string()),
        };

        let secret = [0x42u8; 32];
        let h1 = entry.compute_hmac(&secret).unwrap();
        let h2 = entry.compute_hmac(&secret).unwrap();
        assert_eq!(h1, h2, "HMAC computation is non-deterministic");
    }
}
