//! ADR-009: Audit Entry V2 — RFC 8785 Canonical JSON Serialization.
//!
//! All new audit entries generated in Phase 1+ include `schema_version: 2` and
//! use lexicographically sorted keys (RFC 8785 / JCS) for HMAC computation,
//! making the chain immune to Rust struct field reordering.
//!
//! See: `docs/adr/ADR-009-audit-chain-migration.md`

use hmac::{Hmac, Mac};
use serde::{Deserialize, Serialize};
use serde_json::Value;
use sha2::Sha256;

type HmacSha256 = Hmac<Sha256>;

/// Schema version constant for V2 entries.
pub const SCHEMA_VERSION_V2: u32 = 2;

/// Audit entry V2 — includes explicit `schema_version` field and uses
/// RFC 8785 canonical JSON for deterministic HMAC computation.
///
/// Unlike `AuditEntryV1Legacy`, this struct CAN evolve by adding new optional
/// fields (with `skip_serializing_if`), because HMAC verification uses
/// canonical JSON (sorted keys) rather than struct-declaration-order serialization.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AuditEntryV2 {
    /// Schema version — always `2` for this type.
    pub schema_version: u32,
    /// RFC-3339 timestamp at write time.
    pub ts: String,
    /// Session UUID generated by the gateway.
    pub session_id: String,
    /// Event name (e.g. `tool_allow`, `tool_deny`, `schema_migration_bridge`).
    pub event: String,
    /// Tool name from the MCP `tools/call` request.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_name: Option<String>,
    /// SHA-256 hex of the canonical JSON of the tool arguments.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub params_hash: Option<String>,
    /// Raw params — only present when `include_params = true`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub params: Option<Value>,
    /// Human-readable denial or event reason.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
    /// Policy evaluation latency in milliseconds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub latency_ms: Option<f64>,
    /// OIDC `sub` claim.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub identity_sub: Option<String>,
    /// OIDC `email` claim.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub identity_email: Option<String>,
    /// SHA-256 hash of the active policy file at event time.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub policy_hash: Option<String>,
    /// Client remote IP address.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub request_ip: Option<String>,
    /// Group policy ID that triggered this decision.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub matched_group_id: Option<String>,
    /// Zero-based position within the current log file segment.
    pub entry_index: u64,
    /// HMAC hex of the previous entry.
    pub prev_hmac: String,
    /// HMAC-SHA256 of this entry's RFC 8785 canonical JSON (with `hmac` field excluded).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub hmac: Option<String>,
    /// Migration metadata — present only for `schema_migration_bridge` events.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub migration_metadata: Option<MigrationMetadata>,
    /// Structured verdict explanation — present for explainable block decisions.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub verdict: Option<VerdictExplanation>,
}

/// Metadata attached to a `schema_migration_bridge` entry linking the
/// terminal HMAC of a v1 chain to the genesis of a v2 chain.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MigrationMetadata {
    /// Schema version of the source chain.
    pub from_schema_version: u32,
    /// Schema version of the target chain.
    pub to_schema_version: u32,
    /// Final HMAC hex of the last entry in the terminated v1 chain.
    pub terminal_v1_hmac: String,
    /// HMAC of the bridge entry itself (for chain continuity).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub bridge_signature: Option<String>,
}

/// Structured explanation of a policy decision (RFC 7807-inspired).
///
/// Enables explainable security: the audit log records not just the decision
/// but the reasoning chain that produced it.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VerdictExplanation {
    /// Machine-readable rule ID that triggered this verdict (e.g. `dlp-api-key-001`).
    pub rule_id: String,
    /// Risk category (e.g. `credential_exposure`, `privilege_escalation`).
    pub risk_category: String,
    /// Short evidence snippet (redacted if necessary) showing what triggered the rule.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub evidence_snippet: Option<String>,
    /// Human-readable remediation instructions.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub remediation: Option<String>,
}

// ─── RFC 8785 Canonical JSON ───────────────────────────────────────────────

/// Produce RFC 8785 (JCS) canonical JSON bytes from a `serde_json::Value`.
///
/// Keys are sorted lexicographically by their UTF-16 code unit representation.
/// For ASCII-only keys (our case), this is equivalent to byte-order sorting.
/// Numbers use shortest representation without trailing zeros.
pub fn canonical_json_bytes(value: &Value) -> Vec<u8> {
    let mut buf = Vec::new();
    write_canonical(value, &mut buf);
    buf
}

/// Write canonical JSON into a byte buffer (recursive).
fn write_canonical(value: &Value, buf: &mut Vec<u8>) {
    match value {
        Value::Null => buf.extend_from_slice(b"null"),
        Value::Bool(b) => {
            if *b {
                buf.extend_from_slice(b"true");
            } else {
                buf.extend_from_slice(b"false");
            }
        }
        Value::Number(n) => {
            // RFC 8785 §3.2.2.3: Use shortest representation.
            let s = n.to_string();
            buf.extend_from_slice(s.as_bytes());
        }
        Value::String(s) => {
            // RFC 8785 §3.2.2.2: JSON string escaping.
            buf.push(b'"');
            for ch in s.chars() {
                match ch {
                    '"' => buf.extend_from_slice(b"\\\""),
                    '\\' => buf.extend_from_slice(b"\\\\"),
                    '\x08' => buf.extend_from_slice(b"\\b"),
                    '\x0C' => buf.extend_from_slice(b"\\f"),
                    '\n' => buf.extend_from_slice(b"\\n"),
                    '\r' => buf.extend_from_slice(b"\\r"),
                    '\t' => buf.extend_from_slice(b"\\t"),
                    c if (c as u32) < 0x20 => {
                        // Control characters use \u00XX
                        buf.extend_from_slice(format!("\\u{:04x}", c as u32).as_bytes());
                    }
                    c => {
                        let mut utf8_buf = [0u8; 4];
                        buf.extend_from_slice(c.encode_utf8(&mut utf8_buf).as_bytes());
                    }
                }
            }
            buf.push(b'"');
        }
        Value::Array(arr) => {
            buf.push(b'[');
            for (i, item) in arr.iter().enumerate() {
                if i > 0 {
                    buf.push(b',');
                }
                write_canonical(item, buf);
            }
            buf.push(b']');
        }
        Value::Object(map) => {
            // RFC 8785 §3.2.3: Sort keys by UTF-16 code units.
            // For ASCII keys, this is identical to byte-order sorting.
            let mut keys: Vec<&String> = map.keys().collect();
            keys.sort_by(|a, b| {
                let a_units: Vec<u16> = a.encode_utf16().collect();
                let b_units: Vec<u16> = b.encode_utf16().collect();
                a_units.cmp(&b_units)
            });

            buf.push(b'{');
            for (i, key) in keys.iter().enumerate() {
                if i > 0 {
                    buf.push(b',');
                }
                // Write key as JSON string
                write_canonical(&Value::String((*key).clone()), buf);
                buf.push(b':');
                write_canonical(&map[*key], buf);
            }
            buf.push(b'}');
        }
    }
}

impl AuditEntryV2 {
    /// Compute HMAC-SHA256 of this V2 entry using RFC 8785 canonical JSON.
    ///
    /// The `hmac` and `migration_metadata.bridge_signature` fields are excluded
    /// from the canonical form before hashing.
    pub fn compute_hmac(&self, session_secret: &[u8]) -> Result<String, String> {
        let mut verify_copy = self.clone();
        verify_copy.hmac = None;
        // Strip bridge_signature from migration metadata during HMAC computation.
        if let Some(ref mut meta) = verify_copy.migration_metadata {
            meta.bridge_signature = None;
        }

        // Serialize to serde_json::Value first, then canonicalize.
        let value = serde_json::to_value(&verify_copy)
            .map_err(|e| format!("V2 serialization error: {}", e))?;

        let canonical_bytes = canonical_json_bytes(&value);

        let mut mac = HmacSha256::new_from_slice(session_secret).expect("HMAC key length is valid");
        mac.update(&canonical_bytes);
        Ok(hex::encode(mac.finalize().into_bytes()))
    }

    /// Verify that the stored HMAC matches a freshly computed one.
    pub fn verify_hmac(&self, session_secret: &[u8]) -> Result<bool, String> {
        let stored = self.hmac.as_deref().unwrap_or_default();
        let computed = self.compute_hmac(session_secret)?;
        Ok(stored == computed)
    }
}

// ─── Unit Tests ────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn test_canonical_json_key_ordering() {
        let obj = json!({"z": 1, "a": 2, "m": 3});
        let canonical = String::from_utf8(canonical_json_bytes(&obj)).unwrap();
        assert_eq!(canonical, r#"{"a":2,"m":3,"z":1}"#);
    }

    #[test]
    fn test_canonical_json_nested_objects() {
        let obj = json!({"b": {"z": 1, "a": 2}, "a": 3});
        let canonical = String::from_utf8(canonical_json_bytes(&obj)).unwrap();
        assert_eq!(canonical, r#"{"a":3,"b":{"a":2,"z":1}}"#);
    }

    #[test]
    fn test_canonical_json_string_escaping() {
        let obj = json!({"key": "hello\nworld\t\"escaped\""});
        let canonical = String::from_utf8(canonical_json_bytes(&obj)).unwrap();
        assert_eq!(canonical, r#"{"key":"hello\nworld\t\"escaped\""}"#);
    }

    #[test]
    fn test_canonical_json_null_bool_number() {
        let obj = json!({"n": null, "b": true, "f": false, "i": 42, "d": 1.5});
        let canonical = String::from_utf8(canonical_json_bytes(&obj)).unwrap();
        // Keys sorted: b, d, f, i, n
        assert_eq!(canonical, r#"{"b":true,"d":1.5,"f":false,"i":42,"n":null}"#);
    }

    #[test]
    fn test_canonical_json_array() {
        let obj = json!({"arr": [3, 1, 2], "key": "val"});
        let canonical = String::from_utf8(canonical_json_bytes(&obj)).unwrap();
        assert_eq!(canonical, r#"{"arr":[3,1,2],"key":"val"}"#);
    }

    #[test]
    fn test_v2_hmac_determinism() {
        let entry = AuditEntryV2 {
            schema_version: SCHEMA_VERSION_V2,
            ts: "2026-06-15T12:00:00Z".to_string(),
            session_id: "v2-test".to_string(),
            event: "tool_allow".to_string(),
            tool_name: Some("read_file".to_string()),
            params_hash: None,
            params: None,
            reason: None,
            latency_ms: Some(2.3),
            identity_sub: None,
            identity_email: None,
            policy_hash: None,
            request_ip: None,
            matched_group_id: None,
            entry_index: 0,
            prev_hmac: "0000000000000000000000000000000000000000000000000000000000000000"
                .to_string(),
            hmac: Some("will-be-stripped".to_string()),
            migration_metadata: None,
            verdict: None,
        };

        let secret = [0x42u8; 32];
        let h1 = entry.compute_hmac(&secret).unwrap();
        let h2 = entry.compute_hmac(&secret).unwrap();
        assert_eq!(h1, h2, "V2 HMAC computation is non-deterministic");
    }

    #[test]
    fn test_v2_field_order_independence() {
        // V2 canonical JSON sorts keys, so field declaration order doesn't matter.
        // We test this by verifying the HMAC is the same regardless of how serde
        // orders the fields internally.
        let entry = AuditEntryV2 {
            schema_version: SCHEMA_VERSION_V2,
            ts: "2026-01-01T00:00:00Z".to_string(),
            session_id: "order-test".to_string(),
            event: "tool_deny".to_string(),
            tool_name: Some("bash".to_string()),
            params_hash: None,
            params: None,
            reason: Some("blocked".to_string()),
            latency_ms: None,
            identity_sub: None,
            identity_email: None,
            policy_hash: None,
            request_ip: None,
            matched_group_id: None,
            entry_index: 5,
            prev_hmac: "abcdef".to_string(),
            hmac: None,
            migration_metadata: None,
            verdict: None,
        };

        let secret = [0xAB; 32];

        // Compute canonical bytes directly from a manually-ordered JSON object
        // to verify that key sorting makes the result order-independent.
        let value = serde_json::to_value(&entry).unwrap();
        let canonical = String::from_utf8(canonical_json_bytes(&value)).unwrap();

        // All keys should appear in lexicographic order
        let key_positions: Vec<usize> = [
            "\"entry_index\"",
            "\"event\"",
            "\"prev_hmac\"",
            "\"reason\"",
            "\"schema_version\"",
            "\"session_id\"",
            "\"tool_name\"",
            "\"ts\"",
        ]
        .iter()
        .map(|k| canonical.find(k).unwrap())
        .collect();

        // Verify keys appear in ascending position order (i.e. sorted)
        for i in 1..key_positions.len() {
            assert!(
                key_positions[i] > key_positions[i - 1],
                "Key ordering violation in canonical JSON"
            );
        }

        // HMAC should be deterministic
        let hmac = entry.compute_hmac(&secret).unwrap();
        assert!(!hmac.is_empty());
    }

    #[test]
    fn test_migration_bridge_entry() {
        let bridge = AuditEntryV2 {
            schema_version: SCHEMA_VERSION_V2,
            ts: "2026-07-01T00:00:00Z".to_string(),
            session_id: "migration-session".to_string(),
            event: "schema_migration_bridge".to_string(),
            tool_name: None,
            params_hash: None,
            params: None,
            reason: None,
            latency_ms: None,
            identity_sub: None,
            identity_email: None,
            policy_hash: None,
            request_ip: None,
            matched_group_id: None,
            entry_index: 0,
            prev_hmac: "0000000000000000000000000000000000000000000000000000000000000000"
                .to_string(),
            hmac: None,
            migration_metadata: Some(MigrationMetadata {
                from_schema_version: 1,
                to_schema_version: 2,
                terminal_v1_hmac: "e3b0c44298fc1c149afbf4c8996fb924".to_string(),
                bridge_signature: None,
            }),
            verdict: None,
        };

        let secret = [0x55; 32];
        let hmac = bridge.compute_hmac(&secret).unwrap();
        assert!(!hmac.is_empty());
        // Verify bridge_signature is excluded from HMAC computation
        let hmac2 = bridge.compute_hmac(&secret).unwrap();
        assert_eq!(hmac, hmac2);
    }
}
