//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by hand (matches controller-gen output for agentcontrol_types.go).
// Regenerate with: controller-gen object paths="./..."

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// ── IdentityConfig ───────────────────────────────────────────────────────

func (in *IdentityConfig) DeepCopyInto(out *IdentityConfig) {
	*out = *in
}

func (in *IdentityConfig) DeepCopy() *IdentityConfig {
	if in == nil {
		return nil
	}
	out := new(IdentityConfig)
	in.DeepCopyInto(out)
	return out
}

// ── NetworkPolicyConfig ──────────────────────────────────────────────────

func (in *NetworkPolicyConfig) DeepCopyInto(out *NetworkPolicyConfig) {
	*out = *in
	if in.AgentPodSelector != nil {
		in, out := &in.AgentPodSelector, &out.AgentPodSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.GatewayPodSelector != nil {
		in, out := &in.GatewayPodSelector, &out.GatewayPodSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

func (in *NetworkPolicyConfig) DeepCopy() *NetworkPolicyConfig {
	if in == nil {
		return nil
	}
	out := new(NetworkPolicyConfig)
	in.DeepCopyInto(out)
	return out
}

// ── AgentControlPolicySpec ──────────────────────────────────────────────────

func (in *AgentControlPolicySpec) DeepCopyInto(out *AgentControlPolicySpec) {
	*out = *in
	out.Identity = in.Identity
	in.NetworkPolicy.DeepCopyInto(&out.NetworkPolicy)
}

func (in *AgentControlPolicySpec) DeepCopy() *AgentControlPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AgentControlPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// ── AgentControlPolicyStatus ────────────────────────────────────────────────

func (in *AgentControlPolicyStatus) DeepCopyInto(out *AgentControlPolicyStatus) {
	*out = *in
}

func (in *AgentControlPolicyStatus) DeepCopy() *AgentControlPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AgentControlPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// ── AgentControlPolicy ──────────────────────────────────────────────────────

func (in *AgentControlPolicy) DeepCopyInto(out *AgentControlPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

func (in *AgentControlPolicy) DeepCopy() *AgentControlPolicy {
	if in == nil {
		return nil
	}
	out := new(AgentControlPolicy)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentControlPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// ── AgentControlPolicyList ──────────────────────────────────────────────────

func (in *AgentControlPolicyList) DeepCopyInto(out *AgentControlPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AgentControlPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *AgentControlPolicyList) DeepCopy() *AgentControlPolicyList {
	if in == nil {
		return nil
	}
	out := new(AgentControlPolicyList)
	in.DeepCopyInto(out)
	return out
}

func (in *AgentControlPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}