-- Migration: 000001_init_schema.down.sql
BEGIN;

DROP TABLE IF EXISTS idempotency_records CASCADE;
DROP TABLE IF EXISTS mcp_servers CASCADE;
DROP TABLE IF EXISTS audit_events CASCADE;
DROP TABLE IF EXISTS alerts CASCADE;
DROP TABLE IF EXISTS telemetry_events CASCADE;
DROP TABLE IF EXISTS spend_v2_increase_requests CASCADE;
DROP TABLE IF EXISTS spend_idempotency CASCADE;
DROP TABLE IF EXISTS spend_events CASCADE;
DROP TABLE IF EXISTS spend_reservations CASCADE;
DROP TABLE IF EXISTS budget_windows CASCADE;
DROP TABLE IF EXISTS spend_policy_versions CASCADE;
DROP TABLE IF EXISTS spend_policies CASCADE;
DROP TABLE IF EXISTS price_book_items CASCADE;
DROP TABLE IF EXISTS price_book_versions CASCADE;
DROP TABLE IF EXISTS price_books CASCADE;
DROP TABLE IF EXISTS policy_templates CASCADE;
DROP TABLE IF EXISTS group_policy_versions CASCADE;
DROP TABLE IF EXISTS policy_versions CASCADE;
DROP TABLE IF EXISTS policies CASCADE;
DROP TABLE IF EXISTS provider_keys CASCADE;
DROP TABLE IF EXISTS virtual_keys CASCADE;
DROP TABLE IF EXISTS device_tamper_logs CASCADE;
DROP TABLE IF EXISTS device_compliance_reports CASCADE;
DROP TABLE IF EXISTS device_certificates CASCADE;
DROP TABLE IF EXISTS enrollment_transactions CASCADE;
DROP TABLE IF EXISTS enrollment_tokens CASCADE;
DROP TABLE IF EXISTS devices CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS auth_providers CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS organizations CASCADE;

DROP TYPE IF EXISTS token_status CASCADE;
DROP TYPE IF EXISTS credential_status CASCADE;
DROP TYPE IF EXISTS device_state CASCADE;
DROP TYPE IF EXISTS agent_status CASCADE;
DROP TYPE IF EXISTS alert_severity CASCADE;
DROP TYPE IF EXISTS event_decision CASCADE;

COMMIT;
